### ISSUE TITLE
Tag value containing `=` does not give correct tag value.

### ISSUE THREAD

**Issue by swaprenge** [philip-gcex/parse-fix#1] opened 2023-02-16 09:09 UTC
My fix message is having one tag like `848=20003=3;20004=Y;20012=Y|21001=1.3466471|10=125` string.
When I use `parseFixMsg` method to parse the fix message, value for 848 is only 20003 instead of 20003=3;20004=Y;20012=Y

Can you please check the above issue. 
I checked the code and can see that, we are splitting by '=' symbol in `parseFixMsg` method, which does not support above fix message string.
Let me know if you need any additional details.

Would love to hear back from you.

Thanks.

**Comment by philip-gcex** [comment] 2023-02-16 12:20
I've published v0.0.7, which I think should address this issue. It was caused by using `split("=")`: I've fixed by re-joining the tail of the output array from this. Let  me know if any problems.

**Comment by swaprenge** [comment] 2023-02-17 04:38
@philip-gcex thanks for the quick help, I also tried to fix it by using split in this way:
`split(/=(.*)/s)` 
instead of `split('=')`

I will update to v0.0.7 and let you know if this is fixed.

**Comment by philip-gcex** [comment] 2023-02-20 10:42
Let me know if any issues...

**Closed as completed by philip-gcex** 2023-02-20 10:42 UTC
